% Sample data (54000 x 10)
data = csvread('data/data_pig.csv');
title={'time', 'name', 'fIAV_muscle1', 'fLogD_muscle1', 'fMAV_muscle1', 'fMAX_muscle1', 'fNZM_muscle1', 'fSSC_muscle1', 'fRMS_muscle1',...
    'fIAV_muscle2', 'fLogD_muscle2', 'fVAR_muscle1', 'fWA_muscle1','fWL_muscle1', 'fZC_muscle1','fARC_muscle1','fFME_muscle1', 'fFMD_muscle1',...
    'fMAV_muscle2', 'fMAX_muscle2', 'fNZM_muscle2', 'fRMS_muscle2', 'fSSC_muscle2', 'fVAR_muscle2', 'fWA_muscle2','fWL_muscle2','fZC_muscle2',...
    'fARC_muscle2', 'fFME_muscle2', 'fFMD_muscle2', 'fIAV_muscle3', 'fLogD_muscle3', 'fMAV_muscle3', 'fMAX_muscle3','fNZM_muscle3','fRMS_muscle3',...
    'fSSC_muscle3', 'fVAR_muscle3', 'fWA_muscle3', 'fWL_muscle3', 'fZC_muscle3', 'fARC_muscle3', 'fFME_muscle3', 'fFMD_muscle3', 'fIAV_muscle4',...
    'fLogD_muscle4', 'fMAV_muscle4', 'fMAX_muscle4', 'fNZM_muscle4', 'fRMS_muscle4', 'fSSC_muscle4', 'fVAR_muscle4', 'fWA_muscle4', 'fWL_muscle4',...
    'fZC_muscle4', 'fARC_muscle4', 'fFME_muscle4', 'fFMD_muscle4', 'EM_muscle1', 'EM_muscle2', 'force', 'fIAV_glove', 'fLogD_glove', 'fMAV_glove',...
    'fMAX_glove', 'fNZM_glove', 'fRMS_glove', 'fSSC_glove', 'fVAR_glove', 'fWA_glove', 'fWL_glove', 'fZC_glove', 'fARC_glove', 'fFME_glove',...
    'fFMD_glove', 'EM_muscle3', 'EM_muscle4', 'EM_glove', 'classe'};

%num_window,name,fIAV_muscle1,fLogD_muscle1,fMAV_muscle1,fMAX_muscle1,fNZM_muscle1,fRMS_muscle1,fSSC_muscle1,fVAR_muscle1,fWA_muscle1,fWL_muscle1,fZC_muscle1,fARC_muscle1,fFME_muscle1,fFMD_muscle1,fIAV_muscle2,fLogD_muscle2,fMAV_muscle2,fMAX_muscle2,fNZM_muscle2,fRMS_muscle2,fSSC_muscle2,fVAR_muscle2,fWA_muscle2,fWL_muscle2,fZC_muscle2,fARC_muscle2,fFME_muscle2,fFMD_muscle2,fIAV_muscle3,fLogD_muscle3,fMAV_muscle3,fMAX_muscle3,fNZM_muscle3,fRMS_muscle3,fSSC_muscle3,fVAR_muscle3,fWA_muscle3,fWL_muscle3,fZC_muscle3,fARC_muscle3,fFME_muscle3,fFMD_muscle3,fIAV_muscle4,fLogD_muscle4,fMAV_muscle4,fMAX_muscle4,fNZM_muscle4,fRMS_muscle4,fSSC_muscle4,fVAR_muscle4,fWA_muscle4,fWL_muscle4,fZC_muscle4,fARC_muscle4,fFME_muscle4,fFMD_muscle4,
%EM_muscle1,EM_muscle2,force1,...
%fIAV_glove,fLogD_glove,fMAV_glove,fMAX_glove,fNZM_glove,fRMS_glove,fSSC_glove,fVAR_glove,fWA_glove,fWL_glove,fZC_glove,fARC_glove,fFME_glove,...
%fFMD_glove,EM_muscle3,EM_muscle4,EM_glove,classe

for i=1:10
    % Cross varidation (train: 60%, test: 40%)
    cv = cvpartition(size(data,1),'HoldOut',0.4);
    idx = cv.test;

    % Separate to training and test data
    csvwrite(['data/data_pig_train', num2str(i), '.csv'], data(~idx,:));    
    csvwrite(['data/data_pig_test', num2str(i), '.csv'], data(idx,:));    

        
    
end